version: '3'
services:
  app:
    container_name: bank-spring
    image: bank-spring
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      - dbpostgresql
      
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=postgres
      - POSTGRES_DB=banque2